application: markupgen
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: html/stylesheets

- url: /.*
  script: markgen.app

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"